name: Robot
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  exec:
    timeout-minutes: 5
    runs-on: ubuntu-18.04
    steps:
      - name: boost+chromium
        # https://launchpad.net/ubuntu/+source/chromium-browser/101.0.4951.64-0ubuntu0.18.04.1
        run: sudo apt-get update && sudo apt-get install -yq libboost-dev chromium-browser=101.0.4951.64
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Run robot
        run: xvfb-run npm run exec
      - uses: actions/upload-artifact@v4
        with:
          name: nesting
          path: test-results/
          retention-days: 1
